//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WagenParkSolo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Auto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Auto()
        {
            this.Factuurregels = new HashSet<Factuurregel>();
        }
    
        public int Autonummer { get; set; }
        public string Merk { get; set; }
        public string Kenteken { get; set; }
        public string Model { get; set; }
        public string Brandstof { get; set; }
        public Nullable<int> Kmstand { get; set; }
        public Nullable<decimal> Kostperdag { get; set; }
        public byte[] Foto { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Factuurregel> Factuurregels { get; set; }
    }
}
