//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WagenParkSolo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Factuur
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Factuur()
        {
            this.Factuurregels = new HashSet<Factuurregel>();
        }
    
        public int Factuurnummer { get; set; }
        public Nullable<System.DateTime> Factuurdatum { get; set; }
        public string Klantnummer { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Factuurregel> Factuurregels { get; set; }
    }
}
