//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WagenParkSolo.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class WagenparkEntities : DbContext
    {
        public WagenparkEntities()
            : base("name=WagenparkEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<Auto> Autoes { get; set; }
        public virtual DbSet<Factuur> Factuurs { get; set; }
        public virtual DbSet<Factuurregel> Factuurregels { get; set; }
    
        public virtual ObjectResult<spSelectReservations_Result> spSelectReservations(string loggedin)
        {
            var loggedinParameter = loggedin != null ?
                new ObjectParameter("Loggedin", loggedin) :
                new ObjectParameter("Loggedin", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spSelectReservations_Result>("spSelectReservations", loggedinParameter);
        }

        public System.Data.Entity.DbSet<WagenParkSolo.Models.spSelectReservations_Result> spSelectReservations_Result { get; set; }
    }
}
